/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness — never touches dependencies */
    get: operations["getHealthz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness — Postgres (Neon) ping and Redis PING, 1 s timeout each */
    get: operations["getReadyz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthStatus: {
      /** @enum {string} */
      status: "ok";
    };
    DependencyCheck: {
      /** @description Dependency name, e.g. `postgres`, `redis` */
      name: string;
      ok: boolean;
      latencyMs?: number;
    };
    Readiness: {
      /** @enum {string} */
      status: "ready";
      dependencies: components["schemas"]["DependencyCheck"][];
    };
    FieldError: {
      /** @description JSON pointer or parameter name of the rejected input */
      field: string;
      /** @description Localized (bn default / en) */
      message: string;
    };
    ProblemErrors: {
      fields?: components["schemas"]["FieldError"][];
    };
    /** @description RFC-7807 problem details with Kushol extensions. */
    Problem: {
      /** @description URI reference identifying the problem type */
      type: string;
      /** @description Short English summary (not for display) */
      title: string;
      status: number;
      /**
       * @description Stable machine code — open set. Core: UNAUTHENTICATED, FORBIDDEN, VALIDATION_FAILED,
       *     TENANT_MISMATCH, NOT_FOUND, NOT_VERIFIED, RATE_LIMITED, QUOTA_EXCEEDED, CONFLICT,
       *     INTERNAL. Module-specific codes are registered in
       *     docs/modules/01-foundations/technical-document.md §10.
       */
      code: string;
      /** @description Localized, user-displayable message (bn default, en on request) */
      message: string;
      requestId: string;
      detail?: string;
      errors?: components["schemas"]["ProblemErrors"];
      /** @description Present on readiness failures — names each dependency and its state */
      dependencies?: components["schemas"]["DependencyCheck"][];
    };
  };
  responses: {
    /** @description Error (RFC-7807) */
    Problem: {
      headers: {
        "X-Request-Id": components["headers"]["XRequestId"];
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
    AcceptLanguage: string;
  };
  requestBodies: never;
  headers: {
    /** @description Request correlation id (incoming value reused when valid, otherwise a uuid v7) */
    XRequestId: string;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Process is alive */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthStatus"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getReadyz: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All dependencies reachable */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
      /** @description One or more dependencies unreachable; `dependencies` names them */
      503: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
}
