/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness — never touches dependencies */
    get: operations["getHealthz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness — Postgres (Neon) ping and Redis PING, 1 s timeout each */
    get: operations["getReadyz"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Complete registration — user + identity + verification request in one transaction
     * @description Public, rate-limit class `auth` (10/hour/IP). Requires a previously verified OTP
     *     (purpose `register`). Hierarchy placement is re-validated server-side against 04 reads.
     *     Tokens are returned only when the phone OTP completed inside the same flow.
     */
    post: operations["postAuthRegister"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/otp/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Issue a 6-digit OTP by SMS or email (passwordless login, owner decision 2026-10-02)
     * @description Public; class `auth`. Answers 202 identically whether or not the phone/email is
     *     registered (no enumeration). Caps: 60 s resend cooldown, 5/hour per target,
     *     200/hour/IP (CGNAT-tolerant), enforced again on resend.
     */
    post: operations["postAuthOtpRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/otp/resend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend a fresh OTP for the same target and purpose */
    post: operations["postAuthOtpResend"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/otp/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify an OTP — login (tokens), or mark verified for register/link
     * @description Public; class `auth` (10 verifies/hour per target, 3 attempts per code). Purpose
     *     `login` returns tokens (an unknown target answers `{status:"unknown_phone"}` or
     *     `{status:"unknown_email"}` and the client continues to registration); purposes
     *     `register`/`link` return `{status:"verified"}` so the follow-up call can prove
     *     possession. Login is passwordless (owner decision 2026-10-02): both phone and email
     *     targets authenticate.
     */
    post: operations["postAuthOtpVerify"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/password/forgot": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a password-reset code by email
     * @description Public; class `auth` (5/hour/email, 100/hour/IP). Always 202.
     */
    post: operations["postAuthPasswordForgot"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/password/reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset a staff/vendor password with the emailed code
     * @description Public; class `auth`. On success every session and refresh family of the user is
     *     revoked. Also serves as the vendor first-password set after 07 approval.
     */
    post: operations["postAuthPasswordReset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate a mobile refresh token (single-use, reuse-detecting)
     * @description Public (token in body); class `auth`. The presented token is revoked (`rotated`) and a
     *     new one is issued in the same family; claims are re-read from the database. Presenting
     *     a revoked token revokes the whole family and is audited (`auth.refresh_reuse`).
     */
    post: operations["postAuthRefresh"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log out the current device (session or refresh family) */
    post: operations["postAuthLogout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/logout-all": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Log out everywhere — every session and refresh family */
    post: operations["postAuthLogoutAll"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/google/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Begin the Google OIDC round-trip (signed state + PKCE)
     * @description Public; class `auth` (20/hour/IP per provider). `intent=link` requires an
     *     authenticated user. Redirects to Google; the callback redirects to the calling
     *     surface (`/auth/sso/return` on web, deep link on the app) with a one-time result code.
     */
    get: operations["getAuthGoogleStart"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/google/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Google OIDC callback — link or create, then redirect with a result code */
    get: operations["getAuthGoogleCallback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/github/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Begin the GitHub OIDC round-trip (signed state + PKCE) */
    get: operations["getAuthGithubStart"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/github/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** GitHub OIDC callback — link or create, then redirect with a result code */
    get: operations["getAuthGithubCallback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The authenticated user's own account
     * @description Authenticate (either scheme); class `auth` relaxed (60/min/user).
     */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update own display name and/or locale
     * @description Role and status are immutable here (FORBIDDEN on attempt).
     */
    patch: operations["patchMe"];
    trace?: never;
  };
  "/api/v1/verification-requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The school's join-request queue
     * @description school_admin sees own school (all roles); student+`is_ambassador` sees same-school
     *     student/guardian requests only; super_admin sees everything. Tenant-scoped server-side.
     */
    get: operations["listVerificationRequests"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/verification-requests/{id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve a join request → user VERIFIED + provisioning enqueued
     * @description Guardian requests carry `{studentUserId}` — the same-school VERIFIED student the
     *     evidence matched; a `guardian_links` row is written in the same transaction.
     *     Already-decided requests answer CONFLICT. Audited `verification.approved`.
     */
    post: operations["approveVerificationRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/verification-requests/{id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reject a join request with a mandatory reason
     * @description school_admin/super_admin only (ambassadors are approve-only). Audited `verification.rejected`.
     */
    post: operations["rejectVerificationRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/school/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The school's user roster
     * @description school_admin (own school from claim); super_admin may pass `?schoolId=`.
     */
    get: operations["listSchoolUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hierarchy/cities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Launch cities for the registration picker
     * @description Public; master data owned by 04 (served from 03's in-memory fake until 04 lands).
     */
    get: operations["listHierarchyCities"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hierarchy/cities/{cityId}/schools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Schools/colleges in a city */
    get: operations["listHierarchySchools"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/hierarchy/schools/{schoolId}/sections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sections of a school (class level is a section attribute) */
    get: operations["listHierarchySections"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/school-requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request onboarding for a school/college not yet listed
     * @description Public; class `auth`. Submitted from registration when the school dropdown has no
     *     match. Carries the institution details plus the point of contact — the application
     *     admin connects with the POC to onboard the institution. Audited `school.requested`.
     */
    post: operations["createSchoolRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/school-requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Review queue for institution requests (Super Admin) */
    get: operations["listSchoolRequests"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/school-requests/{id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve an institution request — POC is contacted for onboarding
     * @description Super Admin only. Audited `school.request_approved`; the institution itself is created by 04's onboarding.
     */
    post: operations["approveSchoolRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/school-requests/{id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject an institution request with a reason */
    post: operations["rejectSchoolRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ws": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * WebSocket gateway (gorilla upgrade — documented contract, not a REST route)
     * @description JWT in the `Authorization` header at upgrade; unauthenticated → HTTP 401, unverified →
     *     close 4401 (`NOT_VERIFIED`). The server resolves the subscribable room set from
     *     hierarchy + memberships — client `subscribe` requests are intersected with that set and
     *     non-member rooms are ignored + logged. Heartbeat ping ≤ 30 s (2 missed → close);
     *     presence keys TTL 60 s.
     *     x-ws-events (client→server): subscribe {rooms[]} · unsubscribe {rooms[]} ·
     *     message.send {clientMsgId, groupId, kind, body?, mediaAssetId?, replyTo?} ·
     *     message.read {groupId, lastReadMessageId} · typing {groupId, state start|stop} · ping.
     *     x-ws-events (server→client): message.new (full ChatMessage) · message.ack
     *     {clientMsgId, id, createdAt} · message.read {groupId, userId, lastReadMessageId} ·
     *     message.deleted {groupId, id, deletedAt} · presence.update {groupId, userId, online} ·
     *     typing {groupId, userId, state} · notice.new (Notice summary) · error (RFC-7807-shaped
     *     {type, title, status}). Reconnect: backoff 1 s → 30 s cap with jitter → re-auth →
     *     re-subscribe → REST catch-up from the latest local cursor → offline queue replay
     *     (dedupe by clientMsgId).
     */
    get: operations["getWs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My groups (official/custom/dm) with unread counts */
    get: operations["listChatGroups"];
    put?: never;
    /**
     * Request a custom club group (pending School Admin approval)
     * @description Verified users only; the group lands as `pending_approval` and its creator becomes `owner` on activation (BR-010).
     */
    post: operations["createChatGroup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/groups/{groupId}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Group history, 50/page, cursor `before`
     * @description Member guard (`FORBIDDEN` otherwise); tombstones are included and marked so renderers can swap them.
     */
    get: operations["listChatMessages"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/groups/{groupId}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add a member (owner/moderator/School Admin) */
    post: operations["addChatGroupMember"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/groups/{groupId}/members/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove a member (moderator+) */
    delete: operations["removeChatGroupMember"];
    options?: never;
    head?: never;
    /** Change a member's role (moderator+/School Admin) */
    patch: operations["updateChatGroupMemberRole"];
    trace?: never;
  };
  "/api/v1/chat/groups/{groupId}/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Set the caller's last_read_message_id (drives seen counts) */
    patch: operations["markChatRead"];
    trace?: never;
  };
  "/api/v1/chat/dm/{peerId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Open or create a DM room
     * @description Same-school verified peer → instant room (`dm:{minUserId}:{maxUserId}`). Cross-school peer without an accepted request → 404 with the request hint.
     */
    get: operations["openDm"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/message-requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Message Request inbox (received) and sent list */
    get: operations["listMessageRequests"];
    put?: never;
    /** Request an out-of-network DM (anti-spam rate limit) */
    post: operations["createMessageRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/message-requests/{id}/accept": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accept a pending request (recipient only) — creates the DM room */
    post: operations["acceptMessageRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/message-requests/{id}/decline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Decline a pending request (recipient only) */
    post: operations["declineMessageRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a message (REST fallback + media sync path; same service as WS message.send) */
    post: operations["sendChatMessage"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/chat/messages/{messageId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Tombstone a message (author ≤ 15 min; moderator/owner/School Admin anytime) */
    delete: operations["deleteChatMessage"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The notice board for my school (+ my sections)
     * @description Pinned first, then reverse-chronological; section notices limited to the caller's sections. Cached 60 s under `notices:school:{id}` / `notices:section:{id}`.
     */
    get: operations["listNotices"];
    put?: never;
    /** Publish a one-way notice (School Admin = school scope; Teacher = own section) */
    post: operations["publishNotice"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notices/{noticeId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Soft-delete a notice (author or School Admin) */
    delete: operations["deleteNotice"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notices/{noticeId}/pin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Toggle the pin (author or School Admin; the only edit path — BR-006) */
    patch: operations["toggleNoticePin"];
    trace?: never;
  };
  "/api/v1/media/upload-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Presigned R2 PUT for one asset (TTL 15 min)
     * @description Kind/size validated against the caps (image 10 MB, PDF 20 MB, voice 5 min); the sniff at confirm is authoritative over the declared mime.
     */
    post: operations["createMediaUploadUrl"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/media/{assetId}/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm an upload — magic-byte sniff decides (INV-6)
     * @description Owner only; TTL ≤ 15 min; sniffed mime must match the kind allowlist (JPEG/PNG/HEIC → image, %PDF → pdf, AAC/m4a → voice). A mismatch is `VALIDATION_FAILED` and no message may reference the asset.
     */
    post: operations["confirmMediaUpload"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/media/{assetId}/download-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Short-lived R2 GET URL for an asset the caller may view
     * @description Authorized by ownership or by membership of a group/notice referencing the asset; archived assets rehydrate first (the response flags it).
     */
    post: operations["createMediaDownloadUrl"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthStatus: {
      /** @enum {string} */
      status: "ok";
    };
    DependencyCheck: {
      /** @description Dependency name, e.g. `postgres`, `redis` */
      name: string;
      ok: boolean;
      latencyMs?: number;
    };
    Readiness: {
      /** @enum {string} */
      status: "ready";
      dependencies: components["schemas"]["DependencyCheck"][];
    };
    FieldError: {
      /** @description JSON pointer or parameter name of the rejected input */
      field: string;
      /** @description Localized (bn default / en) */
      message: string;
    };
    ProblemErrors: {
      fields?: components["schemas"]["FieldError"][];
    };
    /** @description RFC-7807 problem details with Kushol extensions. */
    Problem: {
      /** @description URI reference identifying the problem type */
      type: string;
      /** @description Short English summary (not for display) */
      title: string;
      status: number;
      /**
       * @description Stable machine code — open set. Core: UNAUTHENTICATED, FORBIDDEN, VALIDATION_FAILED,
       *     TENANT_MISMATCH, NOT_FOUND, NOT_VERIFIED, RATE_LIMITED, QUOTA_EXCEEDED, CONFLICT,
       *     INTERNAL. Module-specific codes are registered in
       *     docs/modules/01-foundations/technical-document.md §10.
       */
      code: string;
      /** @description Localized, user-displayable message (bn default, en on request) */
      message: string;
      requestId: string;
      detail?: string;
      errors?: components["schemas"]["ProblemErrors"];
      /** @description Present on readiness failures — names each dependency and its state */
      dependencies?: components["schemas"]["DependencyCheck"][];
    };
    /**
     * @description `vendor` is platform-scoped (`schoolId` null) and never self-registered
     * @enum {string}
     */
    UserRole: "super_admin" | "school_admin" | "teacher" | "student" | "guardian" | "vendor";
    /** @enum {string} */
    UserStatus: "PENDING" | "VERIFIED" | "SUSPENDED";
    /** @enum {string} */
    Locale: "bn" | "en";
    /** @enum {string} */
    Plan: "free" | "pro";
    /** @enum {string} */
    OtpChannel: "sms" | "email";
    /**
     * @description `reset` OTPs are issued internally by `/auth/password/forgot` only
     * @enum {string}
     */
    OtpPurpose: "login" | "register" | "link";
    /** @description Public user shape — phone numbers are always masked */
    User: {
      id: string;
      role: components["schemas"]["UserRole"];
      status: components["schemas"]["UserStatus"];
      locale: components["schemas"]["Locale"];
      fullName: string;
      /** @description e.g. `+8801XXXXXX789` — present when the account has a phone */
      maskedPhone?: string;
      /** @description present when the account has an email */
      email?: string;
      schoolId?: string | null;
      isAmbassador: boolean;
      plan: components["schemas"]["Plan"];
    };
    /**
     * @description `phone`+`otpCode` are required for student/guardian (OTP purpose `register` proven).
     *     Staff may register with `email`+`password` instead (phone optional). `studentCode`
     *     and `relation` are required when role is `guardian`. No class field — the class
     *     level is derived from the section.
     */
    RegisterInput: {
      locale: components["schemas"]["Locale"];
      role: components["schemas"]["UserRole"];
      fullName: string;
      /** @description BD mobile, normalized server-side to E.164 `+880…` */
      phone?: string;
      /** @description The code verified via `/auth/otp/verify` (purpose `register`) */
      otpCode?: string;
      /** Format: email */
      email?: string;
      /** @description Staff registration only (argon2id server-side) */
      password?: string;
      schoolId: string;
      sectionId: string;
      /** @description Guardian only — the child's student ID */
      studentCode?: string;
      /**
       * @description Guardian only
       * @enum {string}
       */
      relation?: "father" | "mother" | "other";
    };
    RegisterResult: {
      data: {
        user: components["schemas"]["User"];
        /** @description Present only when the phone OTP completed in this flow */
        accessToken?: string;
        refreshToken?: string;
        verificationRequest: components["schemas"]["VerificationRequestItem"];
      };
    };
    /** @description Exactly one of `phone` / `email`. */
    OtpRequestInput: {
      phone?: string;
      /** Format: email */
      email?: string;
      purpose?: components["schemas"]["OtpPurpose"];
    };
    OtpSendResult: {
      data: {
        /** Format: date-time */
        sentAt: string;
        cooldownSeconds: number;
        channel: components["schemas"]["OtpChannel"];
      };
    };
    /** @description Exactly one of `phone` / `email` (matching the request channel). */
    OtpVerifyInput: {
      phone?: string;
      /** Format: email */
      email?: string;
      otpCode: string;
      purpose: components["schemas"]["OtpPurpose"];
    };
    OtpVerifyResult: {
      /**
       * @description `login` on a known phone/email returns tokens + user; an unknown target answers
       *     `{status:"unknown_phone"}` or `{status:"unknown_email"}` (deliberate — OTP proves
       *     possession and registration shares the code path). `register`/`link` return
       *     `{status:"verified"}`.
       */
      data: {
        /** @enum {string} */
        status: "ok" | "unknown_phone" | "unknown_email" | "verified";
        accessToken?: string;
        refreshToken?: string;
        user?: components["schemas"]["User"];
      };
    };
    ForgotPasswordInput: {
      /** Format: email */
      email: string;
    };
    ResetPasswordInput: {
      /** Format: email */
      email: string;
      otpCode: string;
      newPassword: string;
    };
    RefreshInput: {
      refreshToken: string;
    };
    RefreshResult: {
      data: {
        accessToken: string;
        refreshToken: string;
      };
    };
    /** @description App clients pass the current refresh token; web relies on the cookie. */
    LogoutInput: {
      refreshToken?: string;
    };
    MeResult: {
      data: components["schemas"]["User"];
    };
    MeUpdateInput: {
      locale?: components["schemas"]["Locale"];
      fullName?: string;
      /** Format: uri */
      avatarUrl?: string;
    };
    /** @enum {string} */
    VerificationRequestStatus: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED";
    VerificationRequestItem: {
      id: string;
      user: {
        fullName: string;
        role: components["schemas"]["UserRole"];
        phoneMasked?: string;
      };
      status: components["schemas"]["VerificationRequestStatus"];
      /** @description `{studentCode, relation}` for guardians; free-form, proof only */
      evidence?: {
        [key: string]: unknown;
      };
      /** @description Present on REJECTED — the bn/en key + params are resolved client-side */
      decisionReason?: string;
      /** Format: date-time */
      createdAt: string;
      reminderCount: number;
    };
    VerificationRequestPage: {
      data: components["schemas"]["VerificationRequestItem"][];
      nextCursor?: string;
    };
    /** @description Guardian requests require `studentUserId` (the matched same-school VERIFIED student). */
    ApproveInput: {
      studentUserId?: string;
    };
    RejectInput: {
      reason: string;
    };
    DecisionResult: {
      data: {
        id: string;
        status: components["schemas"]["VerificationRequestStatus"];
        userStatus?: components["schemas"]["UserStatus"];
      };
    };
    SchoolUser: {
      id: string;
      fullName: string;
      role: components["schemas"]["UserRole"];
      status: components["schemas"]["UserStatus"];
      maskedPhone?: string;
      isAmbassador?: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    HierarchyCity: {
      id: string;
      nameBn: string;
      nameEn: string;
      isLaunchCity: boolean;
    };
    HierarchyCityPage: {
      data: components["schemas"]["HierarchyCity"][];
    };
    HierarchySchool: {
      id: string;
      nameBn: string;
      nameEn: string;
    };
    HierarchySchoolPage: {
      data: components["schemas"]["HierarchySchool"][];
    };
    HierarchySection: {
      id: string;
      /** @description e.g. `6`..`10` — the class dropdown derives its options from these */
      classLevel: string;
      /** @description Section name, e.g. `A`, `B` (bn/en resolved client-side) */
      name: string;
      sessionYear: number;
    };
    HierarchySectionPage: {
      data: components["schemas"]["HierarchySection"][];
    };
    /** @enum {string} */
    SchoolRequestType: "school" | "college";
    /** @enum {string} */
    SchoolRequestStatus: "PENDING" | "APPROVED" | "REJECTED";
    /** @description Submitted from registration when the school dropdown has no match. The POC is whom the application admin connects to onboard the institution. */
    SchoolRequestInput: {
      name: string;
      type: components["schemas"]["SchoolRequestType"];
      cityId: string;
      address?: string;
      pocName: string;
      /** @description BD mobile, normalized server-side to E.164 */
      pocPhone: string;
      /** Format: email */
      pocEmail?: string;
    };
    SchoolRequestCreated: {
      data: {
        id: string;
        status: components["schemas"]["SchoolRequestStatus"];
      };
    };
    SchoolRequest: {
      id: string;
      name: string;
      type: components["schemas"]["SchoolRequestType"];
      cityId?: string;
      address?: string;
      status: components["schemas"]["SchoolRequestStatus"];
      pocName: string;
      /** @description masked for display, e.g. `+8801XXXXXX789` */
      pocPhone: string;
      pocEmail?: string;
      decisionReason?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      decidedAt?: string;
    };
    SchoolRequestPage: {
      data: components["schemas"]["SchoolRequest"][];
      nextCursor?: string;
    };
    SchoolRequestRejectInput: {
      reason: string;
    };
    SchoolRequestDecision: {
      data: {
        id: string;
        status: components["schemas"]["SchoolRequestStatus"];
      };
    };
    SchoolUserPage: {
      data: components["schemas"]["SchoolUser"][];
      nextCursor?: string;
    };
    /** @enum {string} */
    ChatGroupKind: "official" | "custom" | "dm";
    /** @enum {string} */
    ChatGroupStatus: "active" | "pending_approval" | "archived";
    /** @enum {string} */
    ChatMemberRole: "owner" | "moderator" | "member";
    /** @description The other side of a DM room */
    ChatPeer: {
      userId: string;
      name: string;
    };
    ChatGroup: {
      id: string;
      kind: components["schemas"]["ChatGroupKind"];
      /** @description Tenant school — null only for dm */
      schoolId?: string;
      /** @description Official groups bind 1:1 to a section (BR-003) */
      sectionId?: string;
      /** @description Custom group name; official groups are named from the section */
      name?: string;
      status: components["schemas"]["ChatGroupStatus"];
      myRole: components["schemas"]["ChatMemberRole"];
      memberCount: number;
      unreadCount: number;
      peer?: components["schemas"]["ChatPeer"];
      lastMessagePreview?: string;
      /** Format: date-time */
      lastMessageAt?: string;
      /** Format: date-time */
      createdAt: string;
    };
    ChatGroupPage: {
      data: components["schemas"]["ChatGroup"][];
    };
    ChatGroupCreateInput: {
      name: string;
    };
    ChatGroupMember: {
      userId: string;
      name: string;
      role: components["schemas"]["ChatMemberRole"];
      lastReadMessageId?: string;
      /** Format: date-time */
      joinedAt: string;
    };
    ChatGroupMemberInput: {
      userId: string;
      role?: components["schemas"]["ChatMemberRole"];
    };
    ChatGroupRoleInput: {
      role: components["schemas"]["ChatMemberRole"];
    };
    ChatMemberMutationResult: {
      data: {
        groupId: string;
        userId: string;
        removed: boolean;
      };
    };
    /** @enum {string} */
    ChatMessageKind: "text" | "image" | "pdf" | "voice" | "system";
    /** @description The referenced confirmed asset (message render data) */
    ChatMediaRef: {
      assetId: string;
      kind: components["schemas"]["MediaKind"];
      mime: string;
      /** Format: int64 */
      sizeBytes: number;
      width?: number;
      height?: number;
      durationMs?: number;
      fileName?: string;
      status: components["schemas"]["MediaStatus"];
    };
    ChatMessage: {
      id: string;
      groupId: string;
      senderId: string;
      senderName: string;
      kind: components["schemas"]["ChatMessageKind"];
      body?: string;
      media?: components["schemas"]["ChatMediaRef"];
      /** Format: uuid */
      clientMsgId: string;
      /** @description id of the quoted same-group message */
      replyTo?: string;
      /** @description Server-rendered one-line preview of the quoted message */
      replyPreview?: string;
      /**
       * Format: date-time
       * @description Set ⇒ tombstone ("Message deleted")
       */
      deletedAt?: string;
      /** Format: date-time */
      createdAt: string;
    };
    ChatMessagePage: {
      data: components["schemas"]["ChatMessage"][];
      /** @description Opaque cursor for the next (older) page; absent when exhausted */
      nextBefore?: string;
    };
    ChatMessageSendInput: {
      groupId: string;
      /** @enum {string} */
      kind: "text" | "image" | "pdf" | "voice";
      body?: string;
      /** @description Required for image|pdf|voice; asset must be `confirmed` + owned */
      mediaAssetId?: string;
      /** Format: uuid */
      clientMsgId: string;
      replyTo?: string;
    };
    ChatReadInput: {
      lastReadMessageId: string;
    };
    ChatReadResult: {
      data: {
        groupId: string;
        lastReadMessageId: string;
      };
    };
    ChatDeleteResult: {
      data: {
        id: string;
        /** Format: date-time */
        deletedAt: string;
      };
    };
    /** @enum {string} */
    MessageRequestStatus: "pending" | "accepted" | "declined" | "expired";
    MessageRequestUser: {
      userId: string;
      name: string;
      schoolName?: string;
    };
    MessageRequest: {
      id: string;
      fromUser: components["schemas"]["MessageRequestUser"];
      toUser: components["schemas"]["MessageRequestUser"];
      status: components["schemas"]["MessageRequestStatus"];
      /** @description Set on accept — the room both sides open */
      dmGroupId?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      decidedAt?: string;
      /** Format: date-time */
      expiresAt?: string;
    };
    MessageRequestPage: {
      received: components["schemas"]["MessageRequest"][];
      sent: components["schemas"]["MessageRequest"][];
    };
    MessageRequestInput: {
      toUserId: string;
    };
    MessageRequestDecision: {
      data: {
        id: string;
        status: components["schemas"]["MessageRequestStatus"];
        dmGroupId?: string;
      };
    };
    /** @enum {string} */
    NoticeScope: "school" | "section";
    NoticeAuthor: {
      userId: string;
      name: string;
      /** @enum {string} */
      role: "school_admin" | "teacher";
    };
    /** @enum {string} */
    MediaStatus: "pending" | "confirmed" | "archived";
    /** @enum {string} */
    MediaKind: "image" | "pdf" | "voice";
    /** @description Attachment summary embedded in notices/messages */
    MediaAssetSummary: {
      assetId: string;
      kind: components["schemas"]["MediaKind"];
      mime: string;
      /** Format: int64 */
      sizeBytes: number;
      fileName?: string;
      status: components["schemas"]["MediaStatus"];
    };
    Notice: {
      id: string;
      schoolId: string;
      scope: components["schemas"]["NoticeScope"];
      sectionId?: string;
      title: string;
      body: string;
      pinned: boolean;
      attachment?: components["schemas"]["MediaAssetSummary"];
      author: components["schemas"]["NoticeAuthor"];
      /** Format: date-time */
      publishedAt: string;
    };
    NoticePage: {
      data: components["schemas"]["Notice"][];
    };
    NoticeInput: {
      scope: components["schemas"]["NoticeScope"];
      /** @description Required iff scope=section; must be in the caller's school */
      sectionId?: string;
      title: string;
      body: string;
      /** @default false */
      pinned: boolean;
      /** @description A `confirmed` media asset */
      attachmentId?: string;
    };
    NoticeDeleteResult: {
      data: {
        id: string;
        /** Format: date-time */
        deletedAt: string;
      };
    };
    MediaUploadUrlInput: {
      kind: components["schemas"]["MediaKind"];
      /** Format: int64 */
      sizeBytes: number;
      /** @description Client-declared; the sniff at confirm is authoritative */
      mime?: string;
    };
    MediaPresignResult: {
      data: {
        assetId: string;
        /** Format: uri */
        uploadUrl: string;
        /** Format: date-time */
        expiresAt: string;
      };
    };
    MediaConfirmInput: {
      width?: number;
      height?: number;
      durationMs?: number;
    };
    MediaAsset: {
      id: string;
      kind: components["schemas"]["MediaKind"];
      /** @description Sniffed server-side — never trusted from the client */
      mime: string;
      /** Format: int64 */
      sizeBytes: number;
      width?: number;
      height?: number;
      durationMs?: number;
      status: components["schemas"]["MediaStatus"];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      confirmedAt?: string;
    };
    MediaDownloadUrl: {
      data: {
        /** Format: uri */
        downloadUrl: string;
        /** Format: date-time */
        expiresAt: string;
        /** @description True when an archived asset was restored to the hot prefix first */
        rehydrated?: boolean;
      };
    };
  };
  responses: {
    /** @description Error (RFC-7807) */
    Problem: {
      headers: {
        "X-Request-Id": components["headers"]["XRequestId"];
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
    AcceptLanguage: string;
  };
  requestBodies: never;
  headers: {
    /** @description Request correlation id (incoming value reused when valid, otherwise a uuid v7) */
    XRequestId: string;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealthz: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Process is alive */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthStatus"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getReadyz: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All dependencies reachable */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
      /** @description One or more dependencies unreachable; `dependencies` names them */
      503: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  postAuthRegister: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterInput"];
      };
    };
    responses: {
      /** @description Account created `PENDING` with an open verification request */
      201: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegisterResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  postAuthOtpRequest: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OtpRequestInput"];
      };
    };
    responses: {
      /** @description OTP queued for delivery */
      202: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OtpSendResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  postAuthOtpResend: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OtpRequestInput"];
      };
    };
    responses: {
      /** @description OTP queued (identical body to request) */
      202: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OtpSendResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  postAuthOtpVerify: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OtpVerifyInput"];
      };
    };
    responses: {
      /** @description Verification outcome */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OtpVerifyResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  postAuthPasswordForgot: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordInput"];
      };
    };
    responses: {
      /** @description Accepted — a code is sent when the email belongs to a staff/vendor account */
      202: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  postAuthPasswordReset: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordInput"];
      };
    };
    responses: {
      /** @description Password updated; all sessions revoked */
      204: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  postAuthRefresh: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshInput"];
      };
    };
    responses: {
      /** @description Fresh token pair */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RefreshResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  postAuthLogout: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["LogoutInput"];
      };
    };
    responses: {
      /** @description Current session/refresh family revoked */
      204: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  postAuthLogoutAll: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All sessions and refresh families revoked (audited) */
      204: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  getAuthGoogleStart: {
    parameters: {
      query?: {
        intent?: "login" | "link";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to the provider */
      302: {
        headers: {
          /** @description Provider authorization endpoint */
          Location?: string;
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  getAuthGoogleCallback: {
    parameters: {
      query?: {
        code?: string;
        state?: string;
        error?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to the calling surface with `sso_result` (or `sso_error`) */
      302: {
        headers: {
          /** @description Calling surface URL carrying the one-time result or error */
          Location?: string;
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  getAuthGithubStart: {
    parameters: {
      query?: {
        intent?: "login" | "link";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to the provider */
      302: {
        headers: {
          /** @description Provider authorization endpoint */
          Location?: string;
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  getAuthGithubCallback: {
    parameters: {
      query?: {
        code?: string;
        state?: string;
        error?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to the calling surface with `sso_result` (or `sso_error`) */
      302: {
        headers: {
          /** @description Calling surface URL carrying the one-time result or error */
          Location?: string;
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  patchMe: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MeUpdateInput"];
      };
    };
    responses: {
      /** @description Updated user */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listVerificationRequests: {
    parameters: {
      query?: {
        status?: components["schemas"]["VerificationRequestStatus"];
        role?: components["schemas"]["UserRole"];
        cursor?: string;
        limit?: number;
      };
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Queue page */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VerificationRequestPage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  approveVerificationRequest: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApproveInput"];
      };
    };
    responses: {
      /** @description Approved */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DecisionResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  rejectVerificationRequest: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejectInput"];
      };
    };
    responses: {
      /** @description Rejected (reason stored; user notified via 06) */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DecisionResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listSchoolUsers: {
    parameters: {
      query?: {
        /** @description Super Admin only — selects the school (tenant check still applies) */
        schoolId?: string;
        role?: components["schemas"]["UserRole"];
        status?: components["schemas"]["UserStatus"];
        q?: string;
        cursor?: string;
        limit?: number;
      };
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Roster page (names, roles, statuses, masked phones only) */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchoolUserPage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listHierarchyCities: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description City list (launch cities first) */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HierarchyCityPage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listHierarchySchools: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        cityId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description School list */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HierarchySchoolPage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listHierarchySections: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        schoolId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Section list */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HierarchySectionPage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createSchoolRequest: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SchoolRequestInput"];
      };
    };
    responses: {
      /** @description Request queued for admin review */
      202: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchoolRequestCreated"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listSchoolRequests: {
    parameters: {
      query?: {
        status?: components["schemas"]["SchoolRequestStatus"];
        cursor?: string;
        limit?: number;
      };
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request queue page */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchoolRequestPage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  approveSchoolRequest: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Approved */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchoolRequestDecision"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  rejectSchoolRequest: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SchoolRequestRejectInput"];
      };
    };
    responses: {
      /** @description Rejected */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SchoolRequestDecision"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  getWs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Upgrade accepted (socket handed to the gateway hub) */
      101: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      default: components["responses"]["Problem"];
    };
  };
  listChatGroups: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Groups the caller belongs to, last activity first */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatGroupPage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createChatGroup: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatGroupCreateInput"];
      };
    };
    responses: {
      /** @description Request stored (pending_approval) */
      201: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatGroup"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listChatMessages: {
    parameters: {
      query?: {
        /** @description Opaque cursor (created_at+id of the oldest already-loaded message) */
        before?: string;
        limit?: number;
      };
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        groupId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Newest page first */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatMessagePage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  addChatGroupMember: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        groupId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatGroupMemberInput"];
      };
    };
    responses: {
      /** @description Member added */
      201: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatGroupMember"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  removeChatGroupMember: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        groupId: string;
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed (audited) */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatMemberMutationResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  updateChatGroupMemberRole: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        groupId: string;
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatGroupRoleInput"];
      };
    };
    responses: {
      /** @description Role changed (audited) */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatGroupMember"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  markChatRead: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        groupId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatReadInput"];
      };
    };
    responses: {
      /** @description Read pointer stored; WS `message.read` fans out */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatReadResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  openDm: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        peerId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The (idempotent) DM room */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatGroup"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listMessageRequests: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Row-level authorized (from/to only) */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageRequestPage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createMessageRequest: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MessageRequestInput"];
      };
    };
    responses: {
      /** @description Request pending; no room exists yet */
      201: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageRequest"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  acceptMessageRequest: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted; `dmGroupId` carries the room to open */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageRequestDecision"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  declineMessageRequest: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Declined; the sender is politely blocked (BR-004) */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageRequestDecision"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  sendChatMessage: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatMessageSendInput"];
      };
    };
    responses: {
      /** @description The canonical message (replay with the same clientMsgId returns the original row — BR-008) */
      201: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatMessage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteChatMessage: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        messageId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Soft-deleted; WS `message.deleted` fans out */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatDeleteResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  listNotices: {
    parameters: {
      query?: {
        scope?: components["schemas"]["NoticeScope"];
      };
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The visible board */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NoticePage"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  publishNotice: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NoticeInput"];
      };
    };
    responses: {
      /** @description Published; tags busted; `BroadcastTopic` queued for `school-{id}` / `section-{id}` */
      201: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Notice"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  deleteNotice: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        noticeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed from the board (audited) */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NoticeDeleteResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  toggleNoticePin: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        noticeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The notice with its new pin state */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Notice"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createMediaUploadUrl: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MediaUploadUrlInput"];
      };
    };
    responses: {
      /** @description Asset created (`pending`) with the presigned PUT */
      201: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MediaPresignResult"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  confirmMediaUpload: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        assetId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MediaConfirmInput"];
      };
    };
    responses: {
      /** @description Asset confirmed with the sniffed mime */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MediaAsset"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
  createMediaDownloadUrl: {
    parameters: {
      query?: never;
      header?: {
        /** @description `bn` (default) or `en` — selects the language of `Problem.message` */
        "Accept-Language"?: components["parameters"]["AcceptLanguage"];
      };
      path: {
        assetId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Presigned GET (15-min TTL) */
      200: {
        headers: {
          "X-Request-Id": components["headers"]["XRequestId"];
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MediaDownloadUrl"];
        };
      };
      default: components["responses"]["Problem"];
    };
  };
}
